% MATLAB sagen, was angezeigt werden soll.
Text = ['Geben Sie ihren Namen ein, aber nur,\nwenn ', ...
        'gerade nicht Mittwoch ist.\nMittwochs ', ...
        'geben Sie den Namen Ihres\nNachbarn ', ...
        'zur Rechten ein. Wenn jedoch\nam Mittwoch ', ...
        'Vollmond ist, geben Sie\nden Namen des ', ...
        'Nachbarn zur Linken ein: '];

% Den Namen des Nutzers erfragen
% zum Anzeigen auf dem Bildschirm.
Name = input(Text, 's');

% Eine Begrüßung ausgeben, damit 
% sich der Nutzer willkommen fühlt.
disp(['Hallo ', Name])