Text = ['Geben Sie ihren Namen ein, aber nur,\nwenn ', ...
        'gerade nicht Mittwoch ist.\nMittwochs ', ...
        'geben Sie den Namen Ihres\nNachbarn ', ...
        'zur Rechten ein. Wenn jedoch\nam Mittwoch ', ...
        'Vollmond ist, geben Sie\nden Namen des ', ...
        'Nachbarn zur Linken ein: '];
Name = input(Text, 's');
disp(['Hallo ', Name])